# Generated by Django 5.1.7 on 2025-04-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_course_students_remove_enrollment_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
    ]
