# Generated by Django 5.1.7 on 2025-04-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_enrollment_completed_alter_enrollment_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='material',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
    ]
